[CmdletBinding()]
param(
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$WuffsRoot = Join-Path $RepoRoot 'external\wuffs'
$SourceRoot = Join-Path $RepoRoot 'src\stuntmaster\media\wuffs'
$GeneratedRoot = Join-Path $SourceRoot 'generated'
$Generators = @(
    [pscustomobject]@{
        Package = 'stuntmaster_psx'
        Source = Join-Path $SourceRoot 'stuntmaster_psx.wuffs'
        Output = Join-Path $GeneratedRoot 'stuntmaster_psx.c'
    },
    [pscustomobject]@{
        Package = 'stuntmaster_psx'
        Source = Join-Path $SourceRoot 'str.wuffs'
        Output = Join-Path $GeneratedRoot 'stuntmaster_str.c'
    },
    [pscustomobject]@{
        Package = 'stuntmaster_psx'
        Source = Join-Path $SourceRoot 'xa.wuffs'
        Output = Join-Path $GeneratedRoot 'stuntmaster_xa.c'
    },
    [pscustomobject]@{
        Package = 'stuntmaster_psx'
        Source = Join-Path $SourceRoot 'mdec.wuffs'
        Output = Join-Path $GeneratedRoot 'stuntmaster_mdec.c'
    }
)
$ExpectedWuffsCommit = 'ec71f9c6d829ca763fbbc1f7adecc30a89a8ed0a'

$git = (Get-Command git.exe -ErrorAction Stop).Source
$actualWuffsCommit = [string](& $git -c "safe.directory=$WuffsRoot" `
    -C $WuffsRoot rev-parse HEAD)
$actualWuffsCommit = $actualWuffsCommit.Trim()
if ($LASTEXITCODE -ne 0 -or $actualWuffsCommit -ne $ExpectedWuffsCommit) {
    throw "Wuffs checkout must be pinned at $ExpectedWuffsCommit; found $actualWuffsCommit."
}

$go = (Get-Command go.exe -ErrorAction Stop).Source
$goCache = Join-Path $RepoRoot 'build\wuffs-go-cache'
New-Item -ItemType Directory -Force -Path $goCache | Out-Null
$env:GOCACHE = $goCache

function Invoke-WuffsGenerator {
    param(
        [Parameter(Mandatory = $true)][string] $Package,
        [Parameter(Mandatory = $true)][string] $SourcePath
    )

    $startInfo = [Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = $go
    $startInfo.Arguments =
        "run ./cmd/wuffs-c gen -package_name $Package"
    $startInfo.WorkingDirectory = $WuffsRoot
    $startInfo.UseShellExecute = $false
    $startInfo.CreateNoWindow = $true
    $startInfo.RedirectStandardInput = $true
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    $startInfo.StandardOutputEncoding = [Text.UTF8Encoding]::new($false)
    $startInfo.StandardErrorEncoding = [Text.UTF8Encoding]::new($false)

    $process = [Diagnostics.Process]::new()
    $process.StartInfo = $startInfo
    if (-not $process.Start()) {
        throw "Could not start the Wuffs compiler for $Package."
    }
    $standardOutput = $process.StandardOutput.ReadToEndAsync()
    $standardError = $process.StandardError.ReadToEndAsync()
    $source = [IO.File]::ReadAllText($SourcePath).TrimEnd()
    $process.StandardInput.Write($source + "`n")
    $process.StandardInput.Close()
    $process.WaitForExit()
    $generatedBody = $standardOutput.Result
    $compilerError = $standardError.Result
    if ($process.ExitCode -ne 0) {
        throw "Wuffs generation for $Package failed with exit code $($process.ExitCode):`n$compilerError"
    }

    $sourceName = Split-Path -Leaf $SourcePath
    $banner = "// Generated by tools/generate_wuffs_codecs.ps1 from $sourceName.`n" +
        "// Do not edit this file directly.`n`n"
    return ($banner + $generatedBody).Replace("`r`n", "`n")
}

$generatedFiles = @{}
foreach ($generator in $Generators) {
    $generatedFiles[$generator.Output] = Invoke-WuffsGenerator `
        -Package $generator.Package -SourcePath $generator.Source
}

if ($Check) {
    foreach ($generator in $Generators) {
        if (-not (Test-Path -LiteralPath $generator.Output -PathType Leaf)) {
            throw "Generated Wuffs C is missing: $($generator.Output)"
        }
        $checkedIn = [IO.File]::ReadAllText($generator.Output).Replace("`r`n", "`n")
        if ($checkedIn -cne $generatedFiles[$generator.Output]) {
            throw "Generated Wuffs C is stale: $($generator.Output); run tools/generate_wuffs_codecs.ps1."
        }
    }
    Write-Host "Generated Wuffs C is current ($($Generators.Count) files)."
    exit 0
}

foreach ($generator in $Generators) {
    [IO.File]::WriteAllText(
        $generator.Output,
        $generatedFiles[$generator.Output],
        [Text.UTF8Encoding]::new($false))
    Write-Host "Generated Wuffs C: $($generator.Output)"
}
